#!/bin/bash
set -Ceu

docker run -it \
-p 8000:8000 \
-p 5432:5432 \
--name fruit_sales \
--env POSTGRES_USER='myprojectuser' \
--env POSTGRES_DATABASE='myproject' \
--env POSTGRES_PASSWORD='password' \
fruit_sales:1.0 \
/bin/bash
